# Generated by Django 5.2 on 2025-08-02 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('caja', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_cod', models.CharField(default='PRY', max_length=5)),
                ('pais', models.CharField(default='Paraguay', max_length=50)),
                ('naturaleza', models.CharField(choices=[('1', 'Contribuyente'), ('2', 'No Contribuyente')], default='2', max_length=3)),
                ('t_contribuyente', models.CharField(blank=True, choices=[('1', 'Persona Física'), ('2', 'Persona Jurídica')], max_length=1)),
                ('tipo_documento', models.CharField(choices=[('1', 'Cédula paraguaya'), ('2', 'Pasaporte'), ('3', 'Cédula extranjera'), ('4', 'Carnet de residencia'), ('5', 'Innominado'), ('6', 'Tarjeta Diplomática de exoneración fiscal')], default='1', max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('dv', models.CharField(blank=True, max_length=2)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo_cliente', models.CharField(choices=[('MINORISTA', 'Minorista'), ('MAYORISTA', 'Mayorista')], default='MINORISTA')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Debe ser un número de 8 dígitos')], verbose_name='Número de Timbrado')),
                ('tipo_emision', models.CharField(choices=[('FISICO', 'Comprobante Físico'), ('ELECTRONICO', 'Comprobante Electrónico')], default='ELECTRONICO', max_length=20, verbose_name='Tipo de Emisión')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio Vigencia')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin Vigencia')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido')], default='ACTIVO', editable=False, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timbrado',
                'verbose_name_plural': 'Timbrados',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('F', 'FACTURA'), ('T', 'TICKET')], default='T', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=15)),
                ('condicion', models.CharField(blank=True, choices=[('1', 'CONTADO'), ('2', 'CREDITO')], max_length=20, null=True)),
                ('num_doc_asociado', models.CharField(blank=True, max_length=15)),
                ('timbrado_asociado', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Debe ser un número de 8 dígitos')], verbose_name='Timbrado Documento Asociado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('tipo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente')),
                ('timbrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.timbrado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], default='PRODUCTO', max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_iva', models.PositiveIntegerField(default=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen')),
                ('almacen_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_servicio', to='almacen.almacen')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.servicio')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
