# Generated by Django 5.2 on 2025-08-03 12:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='dia_vencimiento_cuotas',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Día de Vencimiento de Cuotas'),
        ),
        migrations.AddField(
            model_name='venta',
            name='entrega_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Entrega Inicial'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_primer_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Primer Vencimiento'),
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(verbose_name='Número de Cuota')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total de la Cuota')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Pendiente')),
                ('dia_vencimiento', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Día de Vencimiento (mes)')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('PARCIAL', 'Pago Parcial')], default='PENDIENTE', max_length=20)),
                ('entrega_inicial', models.BooleanField(default=False, verbose_name='¿Es entrega inicial?')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['venta', 'numero_cuota'],
                'unique_together': {('venta', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre este pago')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.cuentaporcobrar')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
