# Generated by Django 5.2 on 2025-07-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='igv',
        ),
    ]
