# Generated by Django 5.2 on 2025-08-03 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_dia_vencimiento_cuotas_venta_entrega_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto por Cuota'),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_cuotas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)], verbose_name='Número de Cuotas'),
        ),
    ]
