# Generated by Django 5.2 on 2025-08-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ventas', '0003_venta_monto_cuota_venta_numero_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cancelados', to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
    ]
