# Generated by Django 5.2 on 2025-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dv',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
