# Generated by Django 5.2 on 2025-08-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
        ('ventas', '0004_pagocuota_cancelado_pagocuota_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja'),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
