# Generated by Django 5.2 on 2025-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='num_doc_asociado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='timbrado',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='venta',
            name='timbrado_asociado',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(choices=[('F', 'FACTURA'), ('T', 'TICKET'), ('BV', 'BOLETA DE VENTA')], default='T', max_length=20),
        ),
    ]
