# Generated by Django 5.2 on 2025-08-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ventas', '0005_pagocuota_caja_pagocuota_numero_recibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje sobre venta'), ('ENTREGA', 'Porcentaje sobre entrega inicial'), ('FIJO', 'Monto fijo por venta')], default='PORCENTAJE', max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de comisión')),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto fijo de comisión')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_comision', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Configuración de Comisión',
                'verbose_name_plural': 'Configuraciones de Comisiones',
                'unique_together': {('vendedor', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje sobre venta'), ('ENTREGA', 'Porcentaje sobre entrega inicial'), ('FIJO', 'Monto fijo por venta')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre esta comisión')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_ventas', to='usuarios.perfilusuario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventas.venta')),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.configuracioncomision')),
            ],
            options={
                'verbose_name': 'Comisión por Venta',
                'verbose_name_plural': 'Comisiones por Ventas',
                'ordering': ['-creado'],
            },
        ),
    ]
