# Generated by Django 5.2 on 2025-07-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_num_doc_asociado_venta_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='condicion',
            field=models.CharField(blank=True, choices=[('1', 'CONTADO'), ('2', 'CREDITO')], max_length=20, null=True),
        ),
    ]
