# Generated by Django 5.2 on 2025-08-06 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ventas', '0006_configuracioncomision_comisionventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncomision',
            name='monto_fijo',
        ),
        migrations.AlterField(
            model_name='comisionventa',
            name='tipo',
            field=models.CharField(choices=[('PORCENTAJE_VENTA', 'Porcentaje sobre venta total'), ('ENTREGA_INICIAL', 'Entrega inicial como comisión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracioncomision',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de comisión'),
        ),
        migrations.AlterField(
            model_name='configuracioncomision',
            name='tipo',
            field=models.CharField(choices=[('PORCENTAJE_VENTA', 'Porcentaje sobre venta total'), ('ENTREGA_INICIAL', 'Entrega inicial como comisión')], default='PORCENTAJE_VENTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracioncomision',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to=models.Q(('es_vendedor', True), ('usuario__is_staff', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_comision', to='usuarios.perfilusuario'),
        ),
    ]
