# Generated by Django 5.2 on 2025-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='tasa_iva',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
