# Generated by Django 5.2 on 2025-08-09 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfilusuario_comision_entrega_inicial_and_more'),
        ('ventas', '0007_remove_configuracioncomision_monto_fijo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComisionCobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de comisión')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cobrador', models.ForeignKey(limit_choices_to=models.Q(('es_cobrador', True), ('usuario__is_staff', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_comision_cobrador', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Configuración de Comisión para Cobrador',
                'verbose_name_plural': 'Configuraciones de Comisiones para Cobradores',
                'unique_together': {('cobrador', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='ComisionCobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre esta comisión')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_cobros', to='usuarios.perfilusuario')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_cobrador', to='ventas.pagocuota')),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.configuracioncomisioncobrador')),
            ],
            options={
                'verbose_name': 'Comisión por Cobro',
                'verbose_name_plural': 'Comisiones por Cobros',
                'ordering': ['-creado'],
            },
        ),
    ]
