# Generated by Django 5.2 on 2025-08-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_comisioncobrador_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionventa',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='comisionventa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
