# Generated by Django 5.2 on 2025-08-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
        ('usuarios', '0003_remove_perfilusuario_comision_entrega_inicial_and_more'),
        ('ventas', '0010_comisionventa_monto_pagado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('numero_documento', models.CharField(blank=True, max_length=15)),
                ('tipo', models.CharField(choices=[('TOTAL', 'Cancelación total'), ('PARCIAL', 'Devolución parcial')], default='TOTAL', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
                ('timbrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.timbrado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.detalleventa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.notacredito')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Notas de Crédito',
            },
        ),
    ]
