# Generated by Django 5.2 on 2025-08-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_notacredito_detallenotacredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_revertido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.comisionventa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.notacredito')),
            ],
            options={
                'unique_together': {('comision', 'nota_credito')},
            },
        ),
        migrations.AddField(
            model_name='comisionventa',
            name='notas_credito',
            field=models.ManyToManyField(blank=True, related_name='comisiones_afectadas', through='ventas.ComisionNotaCredito', to='ventas.notacredito'),
        ),
    ]
