# Generated by Django 5.2 on 2025-07-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0008_detalleventa_tasa_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NO_GENERADO', 'No generado'), ('BORRADOR', 'Borrador (XML generado)'), ('VALIDADO', 'Validado contra XSD'), ('ENVIADO', 'Enviado al SET'), ('ACEPTADO', 'Aceptado por SET'), ('ERROR', 'Error')], default='NO_GENERADO', max_length=20)),
                ('xml_generado', models.TextField(blank=True, null=True)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('respuesta_set', models.JSONField(blank=True, null=True)),
                ('codigo_set', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_url', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('errores', models.TextField(blank=True, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_electronico', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
            },
        ),
    ]
