# Generated by Django 5.2 on 2025-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('ventas', '0008_detalleventa_tasa_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoelectronico',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoelectronico',
            name='qr_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='documentoelectronico',
            index=models.Index(fields=['estado'], name='facturacion_estado_336041_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoelectronico',
            index=models.Index(fields=['codigo_set'], name='facturacion_codigo__03cf2d_idx'),
        ),
    ]
