# Generated by Django 5.2 on 2025-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20)),
                ('dv', models.CharField(max_length=2)),
                ('contabilidad', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
                ('fdesde', models.DateField(verbose_name='Fecha de inicio')),
                ('fhasta', models.DateField(verbose_name='Fecha de finalización')),
            ],
        ),
    ]
