# Generated by Django 5.2 on 2025-07-27 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('ALMACEN', 'Personal de Almacén'), ('COMPRAS', 'Personal de Compras'), ('CAJA', 'Personal de Caja')], default='ALMACEN', max_length=10)),
                ('tipo_doc', models.CharField(choices=[('1', 'Cédula paraguaya'), ('2', 'Pasaporte'), ('3', 'Cédula extranjera'), ('4', 'Carnet de residencia'), ('9', 'Otro')], default='1', max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa')),
                ('sucursales', models.ManyToManyField(blank=True, to='empresa.sucursal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['usuario__username'],
            },
        ),
    ]
