# Generated by Django 5.2 on 2025-05-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
