# Generated by Django 5.2 on 2025-08-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['usuario__username'], 'permissions': [('es_vendedor', 'Puede realizar ventas y recibir comisiones'), ('es_cobrador', 'Puede realizar cobros y recibir comisiones')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='comision_entrega_inicial',
            field=models.BooleanField(default=False, help_text='Recibe el 100% de la entrega inicial como comisión', verbose_name='Comisión por entrega inicial'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_cobrador',
            field=models.BooleanField(default=False, verbose_name='¿Es cobrador?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_vendedor',
            field=models.BooleanField(default=False, verbose_name='¿Es vendedor?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje base de comisión para el vendedor', max_digits=5, verbose_name='Porcentaje de comisión'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ALMACEN', 'Personal de Almacén'), ('COMPRAS', 'Personal de Compras'), ('CAJA', 'Personal de Caja'), ('VENDEDOR', 'Vendedor'), ('COBRADOR', 'Cobrador')], default='ALMACEN', max_length=10),
        ),
    ]
