# Generated by Django 5.2 on 2025-08-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_options_perfilusuario_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='comision_entrega_inicial',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='porcentaje_comision',
        ),
    ]
