# Generated by Django 5.2 on 2025-08-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='CERRADA', max_length=20)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('punto_expedicion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caja', to='empresa.puntoexpedicion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_responsable', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
                'permissions': [('puede_abrir_caja', 'Puede abrir cajas'), ('puede_cerrar_caja', 'Puede cerrar cajas')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('comprobante', models.CharField(blank=True, max_length=50, unique=True)),
                ('imagen_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/caja/')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
