# Generated by Django 5.2 on 2025-07-27 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('compras', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='caja.caja'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.sesioncaja'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['estado', 'fecha_apertura'], name='caja_sesion_estado_c79432_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='monto_positivo'),
        ),
    ]
