# Generated by Django 5.2 on 2025-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='nombre',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
