# Generated by Django 5.2 on 2025-08-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
        ('ventas', '0011_notacredito_detallenotacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='nota_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas.notacredito'),
        ),
    ]
