# Generated by Django 5.2 on 2025-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_caja_nombre_alter_caja_saldo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
