# Generated by Django 5.2 on 2025-07-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_caja_nombre_alter_caja_saldo_inicial'),
        ('compras', '0004_remove_ordencompra_igv'),
        ('usuarios', '0004_alter_perfilusuario_cedula'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha_apertura'], 'permissions': [('puede_abrir_caja', 'Puede abrir cajas'), ('puede_cerrar_caja', 'Puede cerrar cajas')], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='imagen_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/caja/'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_responsable', to='usuarios.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='comprobante',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='usuarios.perfilusuario'),
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='caja.caja')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.sesioncaja'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='monto_positivo'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['estado', 'fecha_apertura'], name='caja_sesion_estado_c79432_idx'),
        ),
    ]
