# Generated by Django 5.2 on 2025-07-27 23:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre Legal')),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre Comercial')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('dv', models.CharField(blank=True, max_length=1, verbose_name='DV')),
                ('regimen', models.CharField(choices=[('1', 'Régimen de Turismo'), ('2', 'Importador'), ('3', 'Exportador'), ('4', 'Maquila'), ('5', 'Ley N° 60/90'), ('6', 'Régimen del Pequeño Productor'), ('7', 'Régimen del Mediano Productor'), ('8', 'Régimen Contable')], default='6', max_length=20)),
                ('t_contribuyente', models.CharField(choices=[('1', 'Persona Física'), ('2', 'Persona Jurídica')], default='1', max_length=1)),
                ('direccion', models.CharField(verbose_name='Calle principal')),
                ('calle_sec', models.CharField(blank=True, verbose_name='Calle secundaria')),
                ('no_edificio', models.CharField(blank=True, verbose_name='No edificio/piso/dto...')),
                ('departamento_codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('distrito_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('barrio_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('num_casa', models.CharField(default='0', max_length=5, verbose_name='No. de Casa')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logotipo')),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActividadesEconomicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la actividad económica (ej: 62021)', max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción de la actividad económica', max_length=255, verbose_name='Descripción')),
                ('es_principal', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Actividad Económica',
                'verbose_name_plural': 'Actividades Económicas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='001', max_length=3)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('es_principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PuntoExpedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe ser 3 dígitos')], verbose_name='Código')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_expedicion', to='empresa.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Punto de Expedición',
                'verbose_name_plural': 'Puntos de Expedición',
                'ordering': ['sucursal', 'codigo'],
                'unique_together': {('sucursal', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='SecuenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('TICKET', 'Ticket'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito')], max_length=20)),
                ('prefijo', models.CharField(default='', editable=False, max_length=7)),
                ('siguiente_numero', models.PositiveIntegerField(default=1)),
                ('formato', models.CharField(default='{sucursal}-{punto}-{numero:07d}', editable=False, help_text='Formato fijo: CódigoSucursal-CódigoPunto-Número (001-001-0000001)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('punto_expedicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias', to='empresa.puntoexpedicion')),
            ],
            options={
                'verbose_name': 'Secuencia de Documento',
                'verbose_name_plural': 'Secuencias de Documentos',
                'unique_together': {('punto_expedicion', 'tipo_documento')},
            },
        ),
    ]
