# Generated by Django 5.2 on 2025-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuenciadocumento',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('TICKET', 'Ticket'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito'), ('RECIBO_PAGO', 'Recibo de Pago')], max_length=20),
        ),
    ]
