# Generated by Django 5.2 on 2025-07-27 23:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la conversión', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0, help_text='Costo adicional total por conversión', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura_sifen', models.CharField(choices=[('77', 'Unidad - UNI'), ('87', 'Metros - m'), ('2366', 'Costo Por Mil - CPM'), ('2329', 'Unidad Internacional - UI'), ('110', 'Metros cúbicos - M3'), ('86', 'Gramos - g'), ('89', 'Litros - LT'), ('90', 'Miligramos - MG'), ('91', 'Centimetros - CM'), ('92', 'Centimetros cuadrados - CM2'), ('93', 'Centimetros cubicos - CM3'), ('94', 'Pulgadas - PUL'), ('96', 'Milímetros cuadrados - MM2'), ('79', 'Kilogramos s/ metro cuadrado - kg/m2'), ('97', 'Año - AA'), ('98', 'Mes - ME'), ('99', 'Tonelada - TN'), ('100', 'Hora - Hs'), ('101', 'Minuto - Mi'), ('104', 'Determinación - DET'), ('103', 'Yardas - Ya'), ('108', 'Metros - MT'), ('109', 'Metros cuadrados - M2'), ('95', 'Milímetros - MM'), ('666', 'Segundo - Se'), ('102', 'Día - Di'), ('83', 'Kilogramos - kg'), ('88', 'Mililitros - ML'), ('625', 'Kilómetros - Km'), ('660', 'Metro lineal - ml'), ('885', 'Unidad Medida Global - GL'), ('891', 'Por Milaje - pm'), ('869', 'Hectáreas - ha'), ('569', 'Ración - ración')], default='77')),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='empresa.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_minorista', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tasa_iva', models.PositiveIntegerField(choices=[(10, 'Gravadas 10%'), (5, 'Gravadas 5%'), (0, 'Exentas')], default=10)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='almacen.categoria')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_FALTANTE', 'Ajuste por Faltante'), ('AJUSTE_SOBRANTE', 'Ajuste por Sobrante')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ejecuciones', models.PositiveIntegerField(help_text='Cantidad de veces que se ejecutó esta conversión')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('revertido', models.BooleanField(default=False)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.conversionproducto')),
                ('relacion_reversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.registroconversion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.AddField(
            model_name='conversionproducto',
            name='tipo_conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.tipoconversion'),
        ),
        migrations.CreateModel(
            name='ComponenteConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ORIGEN', 'Producto Origen'), ('DESTINO', 'Producto Destino')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de este producto en la conversión')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='almacen.conversionproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
            ],
            options={
                'unique_together': {('conversion', 'producto', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='almacen.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='almacen.producto')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
