# Generated by Django 5.2 on 2025-07-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_trasladoproducto_detalletraslado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('SIMPLE', 'Servicio Simple'), ('COMPUESTO', 'Servicio Compuesto (usa productos)')], default='SIMPLE', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasa_iva', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('duracion_estimada', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='almacen.servicio')),
            ],
            options={
                'unique_together': {('servicio', 'producto')},
            },
        ),
    ]
