# Generated by Django 5.2 on 2025-07-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_servicio_componenteservicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenteservicio',
            options={'verbose_name': 'Componente de Servicio', 'verbose_name_plural': 'Componentes de Servicio'},
        ),
        migrations.AddField(
            model_name='componenteservicio',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
