# Generated by Django 5.2 on 2025-07-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
