# Generated by Django 5.2 on 2025-07-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_remove_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tasa_iva',
            field=models.PositiveIntegerField(choices=[(10, 'Gravadas 10%'), (5, 'Gravadas 5%'), (0, 'Exentas')], default=10),
        ),
    ]
