# Generated by Django 5.2 on 2025-07-02 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_producto_tasa_iva'),
        ('usuarios', '0004_alter_perfilusuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario'),
        ),
    ]
