# Generated by Django 5.2 on 2025-07-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_movimientoinventario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_compra',
            new_name='precio_mayorista',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_venta',
            new_name='precio_minorista',
        ),
    ]
