# Generated by Django 5.2 on 2025-08-02 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('caja', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('dv', models.CharField(blank=True, max_length=2)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('F', 'FACTURA'), ('T', 'TICKET')], default='F', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=15)),
                ('timbrado', models.CharField(blank=True, max_length=8)),
                ('condicion', models.CharField(blank=True, choices=[('1', 'CONTADO'), ('2', 'CREDITO')], max_length=20, null=True)),
                ('plazo_dias', models.PositiveIntegerField(default=0, help_text='Plazo en días para pagos a crédito')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento para pagos a crédito', null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='usuarios.perfilusuario')),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.movimientocaja')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recibido', models.BooleanField(default=False)),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Orden',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_pagar', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('comprobante', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.cuentaporpagar')),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.movimientocaja')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('tipo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=20)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompra')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compras',
            },
        ),
    ]
