# Generated by Django 5.2 on 2025-07-27 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('caja', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('dv', models.CharField(blank=True, max_length=2)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='usuarios.perfilusuario')),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.movimientocaja')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recibido', models.BooleanField(default=False)),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Orden',
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompra')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compras',
            },
        ),
    ]
