# Generated by Django 5.2 on 2025-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='dv',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
    ]
