# Generated by Django 5.2 on 2025-07-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_proveedor_dv_alter_proveedor_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Orden'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='recepcioncompra',
            options={'verbose_name': 'Recepción de Compra', 'verbose_name_plural': 'Recepciones de Compras'},
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompra'),
        ),
    ]
