# Generated by Django 5.2 on 2025-07-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detalleordencompra_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='igv',
        ),
    ]
