# Generated by Django 5.2 on 2025-07-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_alter_caja_options_movimientocaja_imagen_comprobante_and_more'),
        ('compras', '0004_remove_ordencompra_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='movimiento_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.movimientocaja'),
        ),
    ]
